
---CREATE SCHEMA
CREATE SCHEMA STAGING;
CREATE SCHEMA DATAMART;


------------------------------------------
---CREATING STAGING SCHEMA OBJECTS 
------------------------------------------
CREATE TABLE STAGING.STG_TITANIC_SOURCE_DATA (
	PASSENGER_ID INTEGER NOT NULL,
	SURVIVED INTEGER,
	PASSENGER_CLASS INTEGER,
	PASSENGER_NAME VARCHAR(255) MASKED WITH (FUNCTION = 'partial(1, "xxxxx", 1)'),
	PASSENGER_SEX VARCHAR(255),
	PASSENGER_AGE FLOAT,
	SIBLING_SPOUSES INTEGER,
	PARENTS_CHILDREN INTEGER,
	TICKET_ID VARCHAR(255),
	FARE FLOAT,
	CABIN VARCHAR(255),
	EMBARKED VARCHAR(100),
	INGESTION_ID INTEGER,
	CREATED_DATE datetime DEFAULT CURRENT_TIMESTAMP,
	CREATED_BY VARCHAR(255) DEFAULT suser_sname(),
	PRIMARY KEY (PASSENGER_ID)
);


CREATE TABLE STAGING.STG_TITANIC_SOURCE_DATA_HISTORY (
	PASSENGER_ID INTEGER NOT NULL,
	SURVIVED INTEGER,
	PASSENGER_CLASS INTEGER,
	PASSENGER_NAME VARCHAR(255) MASKED WITH (FUNCTION = 'partial(1, "xxxxx", 1)'),
	PASSENGER_SEX VARCHAR(255),
	PASSENGER_AGE FLOAT,
	SIBLING_SPOUSES INTEGER,
	PARENTS_CHILDREN INTEGER,
	TICKET_ID VARCHAR(255),
	FARE FLOAT,
	CABIN VARCHAR(255),
	EMBARKED VARCHAR(100),
	INGESTION_ID INTEGER,
	RECORD_PROCESSSED_FLAG VARCHAR(1),
	RECORD_CHECKSUM BIGINT,
	CREATED_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
	CREATED_BY VARCHAR(255) DEFAULT suser_sname(),
	UPDATED_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
	UPDATED_BY VARCHAR(255) DEFAULT suser_sname(),
	PRIMARY KEY (PASSENGER_ID)
);



----------------------------------------------
---CREATING DATAMART SCHEMA OBJECTS STARTS HERE  
----------------------------------------------

--DATABASE SEQUENCES
CREATE SEQUENCE DATAMART.SEQ_DIM_CABIN  
    AS int  
    START WITH 1  
    INCREMENT BY 1 ;  		

CREATE SEQUENCE DATAMART.SEQ_DIM_SEX  
    AS int  
    START WITH 1  
    INCREMENT BY 1 ;

CREATE SEQUENCE DATAMART.SEQ_DIM_EMBARKED 
    AS int  
    START WITH 1  
    INCREMENT BY 1 ;
	

CREATE SEQUENCE DATAMART.SEQ_DIM_TICKET
    AS int  
    START WITH 1  
    INCREMENT BY 1 ;
	
CREATE SEQUENCE DATAMART.SEQ_DIM_PASSENGER
    AS int  
    START WITH 1  
    INCREMENT BY 1 ;
	
	
CREATE SEQUENCE DATAMART.SEQ_DIM_CLASS
    AS int  
    START WITH 1  
    INCREMENT BY 1 ;	

CREATE SEQUENCE DATAMART.SEQ_DIM_FARE_BRACKET  
    AS int  
    START WITH 1  
    INCREMENT BY 1 ;  	

CREATE SEQUENCE DATAMART.SEQ_FACT_TITANIC
    AS int  
    START WITH 1  
    INCREMENT BY 1 ;	
	
	

------------------------------------------------	
---FACT AND DIMENSION TABLES DROP ANDA CREATE 
------------------------------------------------

CREATE TABLE DATAMART.DIM_CABIN (
	DIM_CABIN_KEY INTEGER DEFAULT (NEXT VALUE FOR DATAMART.SEQ_DIM_CABIN) ,
	CABIN VARCHAR(255),
	CREATED_DATE datetime DEFAULT CURRENT_TIMESTAMP,
	CREATED_BY VARCHAR(255) DEFAULT suser_sname(),
	PRIMARY KEY (DIM_CABIN_KEY),
	CONSTRAINT UNIQUE_CABIN UNIQUE(CABIN) 
);


CREATE TABLE DATAMART.DIM_SEX (
	DIM_SEX_KEY INTEGER DEFAULT (NEXT VALUE FOR DATAMART.SEQ_DIM_SEX) ,
	SEX VARCHAR(255),
	CREATED_DATE datetime DEFAULT CURRENT_TIMESTAMP,
	CREATED_BY VARCHAR(255) DEFAULT suser_sname(),
	PRIMARY KEY (DIM_SEX_KEY),
	CONSTRAINT UNIQUE_SEX UNIQUE(SEX) 
);


CREATE TABLE DATAMART.DIM_EMBARKED (
	DIM_EMBARKED_KEY INTEGER DEFAULT (NEXT VALUE FOR DATAMART.SEQ_DIM_EMBARKED) ,
	EMBARKED VARCHAR(255),
	CREATED_DATE datetime DEFAULT CURRENT_TIMESTAMP,
	CREATED_BY VARCHAR(255) DEFAULT suser_sname(),
	PRIMARY KEY (DIM_EMBARKED_KEY),
	CONSTRAINT UNIQUE_EMBARKED UNIQUE(EMBARKED) 
);


CREATE TABLE DATAMART.DIM_CLASS (
	DIM_CLASS_KEY INTEGER DEFAULT (NEXT VALUE FOR DATAMART.SEQ_DIM_CLASS) ,
	CLASS INTEGER,
	CREATED_DATE datetime DEFAULT CURRENT_TIMESTAMP,
	CREATED_BY VARCHAR(255) DEFAULT suser_sname(),
	PRIMARY KEY (DIM_CLASS_KEY),
	CONSTRAINT UNIQUE_DIM_CLASS UNIQUE(CLASS) 
);



CREATE TABLE DATAMART.DIM_TICKET (
	DIM_TICKET_KEY INTEGER DEFAULT (NEXT VALUE FOR DATAMART.SEQ_DIM_TICKET) ,
	TICKET VARCHAR(255),
	CREATED_DATE datetime DEFAULT CURRENT_TIMESTAMP,
	CREATED_BY VARCHAR(255) DEFAULT suser_sname(),
	PRIMARY KEY (DIM_TICKET_KEY),
	CONSTRAINT UNIQUE_TICKET UNIQUE(TICKET) 
);


CREATE TABLE DATAMART.DIM_FARE_BRACKET (
	DIM_FARE_BRACKET_KEY INTEGER DEFAULT (NEXT VALUE FOR DATAMART.SEQ_DIM_FARE_BRACKET) ,
	FARE_BRACKET VARCHAR(255),
	CREATED_DATE datetime DEFAULT CURRENT_TIMESTAMP,
	CREATED_BY VARCHAR(255) DEFAULT suser_sname(),
	PRIMARY KEY (DIM_FARE_BRACKET_KEY),
	CONSTRAINT UNIQUE_DIM_FARE_BRACKET UNIQUE(FARE_BRACKET) 
);




CREATE TABLE DATAMART.DIM_PASSENGER (
	DIM_PASSENGER_KEY INTEGER DEFAULT (NEXT VALUE FOR DATAMART.SEQ_DIM_PASSENGER) NOT NULL ,
	PASSENGER_ID INTEGER,
	PASSENGER_NAME VARCHAR(255) MASKED WITH (FUNCTION = 'partial(1, "xxxxx", 1)'),
	PASSENGER_AGE FLOAT,
	AGE_BRACKET VARCHAR(255),
	CREATED_DATE datetime DEFAULT CURRENT_TIMESTAMP,
	CREATED_BY VARCHAR(255) DEFAULT suser_sname(),
	UPDATED_DATE datetime DEFAULT CURRENT_TIMESTAMP,
	UPDATED_BY VARCHAR(255) DEFAULT suser_sname(),
	PRIMARY KEY (DIM_PASSENGER_KEY),
	CONSTRAINT UNIQUE_PASSENGER UNIQUE(PASSENGER_ID) 
);


CREATE TABLE DATAMART.FACT_TITANIC (
	FACT_TITANIC_KEY INTEGER DEFAULT (NEXT VALUE FOR DATAMART.SEQ_FACT_TITANIC) NOT NULL,
	DIM_PASSENGER_KEY INTEGER ,
	DIM_EMBARKED_KEY INTEGER,
	DIM_SEX_KEY INTEGER,
	DIM_TICKET_KEY INTEGER,
	DIM_CABIN_KEY INTEGER,
	DIM_CLASS_KEY INTEGER,
	DIM_FARE_BRACKET_KEY INTEGER,
	SURVIVED INTEGER,
	FARE FLOAT,
	SIBLING_SPOUSES INTEGER,
	PARENTS_CHILDREN INTEGER,
	CREATED_DATE datetime DEFAULT CURRENT_TIMESTAMP,
	CREATED_BY VARCHAR(255) DEFAULT suser_sname(),
	UPDATED_DATE datetime DEFAULT CURRENT_TIMESTAMP,
	UPDATED_BY VARCHAR(255) DEFAULT suser_sname(),
	PRIMARY KEY (FACT_TITANIC_KEY),
	CONSTRAINT UNIQUE_DIM_PASSENGER_KEY UNIQUE(DIM_PASSENGER_KEY)
);


--- ONE TIME DATA SEED DIM_FARE_BRACKET
	INSERT INTO DATAMART.DIM_FARE_BRACKET (FARE_BRACKET) VALUES ('0 TO 25');
	INSERT INTO DATAMART.DIM_FARE_BRACKET (FARE_BRACKET) VALUES ('26 TO 50');
	INSERT INTO DATAMART.DIM_FARE_BRACKET (FARE_BRACKET) VALUES ('51 TO 100');
	INSERT INTO DATAMART.DIM_FARE_BRACKET (FARE_BRACKET) VALUES ('101 TO 150');
	INSERT INTO DATAMART.DIM_FARE_BRACKET (FARE_BRACKET) VALUES ('ABOVE 150');
	INSERT INTO DATAMART.DIM_FARE_BRACKET (FARE_BRACKET) VALUES ('MISSING');
	;	




CREATE TABLE DATAMART.DATA_QUALITY_ERRORS (
	ERROR_DESCRIPTION VARCHAR(1000),
	CREATED_DATE datetime DEFAULT CURRENT_TIMESTAMP,
	CREATED_BY VARCHAR(255) DEFAULT suser_sname()
);
