
------------------------------------------------
---STORED PROC FOR LOADING FACT TABLE
------------------------------------------------
CREATE PROCEDURE DATAMART.LOAD_FACT_DATA
AS
	
	--- UPDATE THE CHANGED RECORDS IN FACT TABLE
	UPDATE DATAMART.FACT_TITANIC 
	SET
		DIM_EMBARKED_KEY = SOURCE_DIM.DIM_EMBARKED_KEY,
		DIM_SEX_KEY = SOURCE_DIM.DIM_SEX_KEY,
		DIM_TICKET_KEY = SOURCE_DIM.DIM_TICKET_KEY,
		DIM_CABIN_KEY = SOURCE_DIM.DIM_CABIN_KEY,
		DIM_CLASS_KEY = SOURCE_DIM.DIM_CLASS_KEY,
		DIM_FARE_BRACKET_KEY = SOURCE_DIM.DIM_FARE_BRACKET_KEY,
		SURVIVED = SOURCE_DIM.SURVIVED,
		FARE = SOURCE_DIM.FARE,
		SIBLING_SPOUSES = SOURCE_DIM.SIBLING_SPOUSES,
		PARENTS_CHILDREN = SOURCE_DIM.PARENTS_CHILDREN,
		UPDATED_DATE = CURRENT_TIMESTAMP
	FROM
		DATAMART.FACT_TITANIC SOURCE_FACT
	INNER JOIN 
	(
		SELECT
			DIM_PASSENGER.DIM_PASSENGER_KEY,
			DIM_EMBARKED.DIM_EMBARKED_KEY,
			DIM_SEX.DIM_SEX_KEY,
			DIM_TICKET.DIM_TICKET_KEY,
			DIM_CABIN.DIM_CABIN_KEY,
			DIM_CLASS.DIM_CLASS_KEY,
			DIM_FARE_BRACKET.DIM_FARE_BRACKET_KEY,
			STG.SURVIVED,
			STG.FARE,
			STG.SIBLING_SPOUSES,
			STG.PARENTS_CHILDREN		
		FROM
			STAGING.STG_TITANIC_SOURCE_DATA_HISTORY STG 
			JOIN DATAMART.DIM_PASSENGER ON STG.PASSENGER_ID = DIM_PASSENGER.PASSENGER_ID
			JOIN DATAMART.DIM_SEX ON COALESCE(STG.PASSENGER_SEX, 'MISSING') = DIM_SEX.SEX
			JOIN DATAMART.DIM_EMBARKED ON COALESCE(STG.EMBARKED, 'MISSING') = DIM_EMBARKED.EMBARKED
			JOIN DATAMART.DIM_TICKET ON COALESCE(STG.TICKET_ID, 'MISSING')  = DIM_TICKET.TICKET
			JOIN DATAMART.DIM_CABIN ON COALESCE(STG.CABIN, 'MISSING') = DIM_CABIN.CABIN
			JOIN DATAMART.DIM_CLASS ON COALESCE(STG.PASSENGER_CLASS, -999) = DIM_CLASS.CLASS
			JOIN DATAMART.DIM_FARE_BRACKET ON 
			CASE WHEN ROUND(STG.FARE, 0) BETWEEN 0 AND 25 THEN '0 TO 25'
				 WHEN ROUND(STG.FARE, 0) BETWEEN 26 AND 50 THEN '26 TO 50'
				 WHEN ROUND(STG.FARE, 0) BETWEEN 51 AND 100 THEN '51 TO 100'
				 WHEN ROUND(STG.FARE, 0) BETWEEN 101 AND 150 THEN '101 TO 150'
				 WHEN ROUND(STG.FARE, 0) > 150 THEN 'ABOVE 150'
				 ELSE 'MISSING' END = DIM_FARE_BRACKET.FARE_BRACKET
			WHERE
				STG.RECORD_PROCESSSED_FLAG = 'N'
				AND EXISTS (
						SELECT 1 FROM DATAMART.FACT_TITANIC FACT 
						WHERE DIM_PASSENGER.DIM_PASSENGER_KEY = FACT.DIM_PASSENGER_KEY
					)	
	) SOURCE_DIM
	ON SOURCE_FACT.DIM_PASSENGER_KEY = SOURCE_DIM.DIM_PASSENGER_KEY
	;
		


	---INSERT NEW RECORDS
	INSERT INTO DATAMART.FACT_TITANIC (
		DIM_PASSENGER_KEY,
		DIM_EMBARKED_KEY,
		DIM_SEX_KEY,
		DIM_TICKET_KEY,
		DIM_CABIN_KEY,
		DIM_CLASS_KEY,
		DIM_FARE_BRACKET_KEY,
		SURVIVED,
		FARE,
		SIBLING_SPOUSES,
		PARENTS_CHILDREN
	)
	SELECT
		DIM_PASSENGER.DIM_PASSENGER_KEY,
		DIM_EMBARKED.DIM_EMBARKED_KEY,
		DIM_SEX.DIM_SEX_KEY,
		DIM_TICKET.DIM_TICKET_KEY,
		DIM_CABIN.DIM_CABIN_KEY,
		DIM_CLASS.DIM_CLASS_KEY,
		DIM_FARE_BRACKET.DIM_FARE_BRACKET_KEY,
		STG.SURVIVED,
		STG.FARE,
		STG.SIBLING_SPOUSES,
		STG.PARENTS_CHILDREN		
	FROM
		STAGING.STG_TITANIC_SOURCE_DATA_HISTORY STG 
		JOIN DATAMART.DIM_PASSENGER ON STG.PASSENGER_ID = DIM_PASSENGER.PASSENGER_ID
		JOIN DATAMART.DIM_SEX ON COALESCE(STG.PASSENGER_SEX, 'MISSING') = DIM_SEX.SEX
		JOIN DATAMART.DIM_EMBARKED ON COALESCE(STG.EMBARKED, 'MISSING') = DIM_EMBARKED.EMBARKED
		JOIN DATAMART.DIM_TICKET ON COALESCE(STG.TICKET_ID, 'MISSING')  = DIM_TICKET.TICKET
		JOIN DATAMART.DIM_CABIN ON COALESCE(STG.CABIN, 'MISSING') = DIM_CABIN.CABIN
		JOIN DATAMART.DIM_CLASS ON COALESCE(STG.PASSENGER_CLASS, -999) = DIM_CLASS.CLASS
		JOIN DATAMART.DIM_FARE_BRACKET ON 
		CASE WHEN ROUND(STG.FARE, 0) BETWEEN 0 AND 25 THEN '0 TO 25'
			 WHEN ROUND(STG.FARE, 0) BETWEEN 26 AND 50 THEN '26 TO 50'
			 WHEN ROUND(STG.FARE, 0) BETWEEN 51 AND 100 THEN '51 TO 100'
			 WHEN ROUND(STG.FARE, 0) BETWEEN 101 AND 150 THEN '101 TO 150'
			 WHEN ROUND(STG.FARE, 0) > 150 THEN 'ABOVE 150'
			 ELSE 'MISSING' END = DIM_FARE_BRACKET.FARE_BRACKET
		WHERE
			STG.RECORD_PROCESSSED_FLAG = 'N'
			AND
			NOT EXISTS (
				SELECT 1 FROM DATAMART.FACT_TITANIC FACT 
				WHERE DIM_PASSENGER.DIM_PASSENGER_KEY = FACT.DIM_PASSENGER_KEY
			);
			

	
GO;
