
------------------------------------------------
---STORED PROC FOR LOADING FACT TABLE
------------------------------------------------
CREATE PROCEDURE STAGING.UPDATE_RECORD_PROCESSED_STATUS
AS
	UPDATE STAGING.STG_TITANIC_SOURCE_DATA_HISTORY
	SET RECORD_PROCESSSED_FLAG = 'Y'
	WHERE RECORD_PROCESSSED_FLAG = 'N'
GO;
